from __future__ import annotations

from typing import Callable, Optional

class Config:
    silence_duration: float
    silence_threshold_rms: float

    def __init__(
        self,
        silence_duration: Optional[float] = None,
        silence_threshold_rms: Optional[float] = None,
    ) -> None: ...

    def validate(self) -> None: ...

class Transcriber:
    def __init__(
        self,
        config: Optional[Config] = None,
        model_uri: Optional[str] = None,
        model_path: Optional[str] = None,
    ) -> None: ...

    def start_transcription(self) -> None: ...
    def stop_transcription(self) -> None: ...
    def is_transcribing(self) -> bool: ...
    def get_latest_transcript(self) -> str: ...
    def register_on_complete(self, callback: Callable[[str], None]) -> None: ...
    def wait_until_done(self, timeout: Optional[float] = None) -> bool: ...

def default() -> Transcriber: ...
def ___version() -> str: ...

